export const nativeModules = [
  { id: "visao", label: "Visao Geral", icon: "dashboard", group: "Estrategia", order: 10, active: true },
  { id: "sitemap", label: "Site Map", icon: "route", group: "Estrategia", order: 20, active: true },
  { id: "dashboard", label: "Dashboard Executivo", icon: "dashboard", group: "Gestao", order: 30, active: true },
  { id: "operacional", label: "Dashboard Operacional", icon: "kanban", group: "Gestao", order: 40, active: true },
  { id: "empresas", label: "Empresas", icon: "building", group: "Operacao", order: 50, active: true },
  { id: "acompanhamento", label: "Acompanhamento", icon: "audit", group: "Operacao", order: 60, active: true },
  { id: "diagnostico", label: "Diagnostico", icon: "file-check", group: "Operacao", order: 70, active: true },
  { id: "indicadores", label: "Indicadores", icon: "chart", group: "CERNE", order: 80, active: true },
  { id: "trl", label: "TRL", icon: "rocket", group: "CERNE", order: 90, active: true },
  { id: "evidencias", label: "Evidencias", icon: "file-check", group: "CERNE", order: 100, active: true },
  { id: "documentos", label: "Documentacao", icon: "folder", group: "Conhecimento", order: 110, active: true },
  { id: "planos", label: "Planos de Acao", icon: "kanban", group: "Operacao", order: 120, active: true },
  { id: "mentorias", label: "Mentorias", icon: "calendar", group: "Operacao", order: 130, active: true },
  { id: "relatorios", label: "Relatorios", icon: "report", group: "Inteligencia", order: 140, active: true },
  { id: "powerbi", label: "Power BI", icon: "powerbi", group: "Inteligencia", order: 150, active: true },
  { id: "auditoria", label: "Auditoria", icon: "audit", group: "Governanca", order: 160, active: true },
  { id: "configuracoes", label: "Configuracoes", icon: "settings", group: "Administracao", order: 170, active: true },
  { id: "roadmap", label: "Roadmap", icon: "route", group: "Produto", order: 180, active: true },
  { id: "usuarios", label: "Usuarios", icon: "settings", group: "Futuro", order: 190, active: false },
  { id: "eventos", label: "Eventos", icon: "calendar", group: "Futuro", order: 200, active: false },
  { id: "consultorias", label: "Consultorias", icon: "audit", group: "Futuro", order: 210, active: false },
  { id: "propriedadeIntelectual", label: "Propriedade Intelectual", icon: "file-check", group: "Futuro", order: 220, active: false },
  { id: "editais", label: "Editais", icon: "folder", group: "Futuro", order: 230, active: false },
  { id: "financeiro", label: "Financeiro", icon: "chart", group: "Futuro", order: 240, active: false },
];
